In [1]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd
import glob
import os

def load_and_stack_xlsx(reports_path):
    # get all xlsx files
    files = glob.glob(os.path.join(reports_path, "*.xlsx"))
    
    # read and store dfs
    dfs = []
    for f in files:
        df = pd.read_excel(f)
        df["source_file"] = os.path.basename(f)  # optional but useful
        dfs.append(df)
    
    # stack (row-wise)
    stacked_df = pd.concat(dfs, ignore_index=True)
    
    return stacked_df

In [2]:
reports_path = "/home/sgw3fy/jobs/standard_shortcut/projects/model_editing/repos/instruct_vlm_edit/indep_runs/temp_pred_reports"

In [4]:
reports_df = load_and_stack_xlsx(reports_path)

In [16]:
reports_df.rename(columns={"qa_pair": "qa_id"}, inplace=True)

In [17]:
reports_df_correct_pred = reports_df[reports_df["target"] == reports_df["pred_no_edit"]]
reports_df_incorrect_pred = reports_df[reports_df["target"] != reports_df["pred_no_edit"]]

## Incorrect Predictions Analysis

In [24]:
reports_df_incorrect_pred = reports_df_incorrect_pred.merge(wrong_edit[["qa_id", "wrong_edit_label"]], on="qa_id")

In [27]:
reports_df_incorrect_pred["acc_wrong_edit"] = reports_df_incorrect_pred["pred_wrong_edit"] == reports_df_incorrect_pred["target"]

In [30]:
reports_df_incorrect_pred["wrong_edit_same_no_edit_pred"] = reports_df_incorrect_pred["wrong_edit_label"] == reports_df_incorrect_pred["pred_no_edit"]

In [29]:
reports_df_incorrect_pred["acc_wrong_edit"].value_counts()

acc_wrong_edit
False    364
True      98
Name: count, dtype: int64

NOTE: For more complext experiments, I'll need the UID

In [45]:
reports_df_incorrect_pred

,target,pred_no_edit,gen_no_edit,pred_wrong_edit,gen_wrong_edit,pred_correct_edit,gen_correct_edit,qa_id,source_file,wrong_edit_label,acc_wrong_edit,wrong_edit_same_no_edit_pred
0,baroque architecture,villa,The architectural style of this church is **Goth,villa,The architectural style of this church is **Rena,baroque architecture,The architectural style of this church is **Rena,1581,report_1581.xlsx,villa,False,True
1,capital punishment,torture,"Actually, there is no patron saint associated ...",capital punishment,The cause of death of this church’s patron saint,capital punishment,The cause of death of this church’s patron saint,2312,report_2312.xlsx,suicide,True,False
2,europe,north america,The monastery in the image is **St. Michael,north america,The monastery in the image is located in **Europe,europe,Europe,150,report_150.xlsx,asia,False,False
3,capital punishment,rebellion,The church in question is **Église Saint,rebellion,The cause of death of the person this church is,capital punishment,The cause of death of the person this church is,1081,report_1081.xlsx,war,False,False
4,1623,1618,The inventor of the motor vehicle — widely cre...,1623,"The inventor of the motor vehicle, Karl Benz,",1623,The inventor of the motor vehicle is typically...,225288,report_225288.xlsx,1613,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
457,amsterdam,berlin,The church shown is the **St. Marien,berlin,Cologne,amsterdam,The capital of the country where this church i...,228066,report_228066.xlsx,cologne,False,False
458,9596961,11476747,The cultural heritage shown in the image is lo...,9596961,7358472 square kilometers,9596961,The area of the sovereign state where this cul...,468759,report_468759.xlsx,7358472,True,False
459,machaerus,england,The church in the image is **St. John,denmark,Norway,machaerus,Machaerus,40203,report_40203.xlsx,norway,False,False
460,right,left,The country where this castle is located is **...,left,left,right,Right-hand driveThe castle in the image is,22420,report_22420.xlsx,left,False,True
461,right,left,The driving side of **Greece** — the,left,left,right,right,3863,report_3863.xlsx,left,False,True

In [44]:
reports_df_incorrect_pred[reports_df_incorrect_pred["acc_wrong_edit"]][["pred_wrong_edit", "gen_wrong_edit", "wrong_edit_label"]][10:20]

,pred_wrong_edit,gen_wrong_edit,wrong_edit_label
36,united kingdom,The church shown in the image is located in **,congo
39,505990,671904,671904
45,europe,The park shown in the image is **Kol,africa
52,europe,The cemetery is located in **Europe**.The,asia
53,archangel michael,The patron saint of the sovereign state where ...,thomas aquinas
54,397,The person for whom this church is named died in,404
74,643801,The area of the country where this château,760300
87,united states,"Based on the image provided, the church buildi...",macedonia
89,europe,The architectural complex shown — a wooden bel...,australia
93,archangel michael,The patron saint of the country in which this ...,saint peter

## Correct Predictions Analysis

In [35]:
reports_df_correct_pred = reports_df_correct_pred.merge(wrong_edit[["qa_id", "wrong_edit_label"]], on="qa_id")

In [36]:
reports_df_correct_pred["acc_wrong_edit"] = reports_df_correct_pred["pred_wrong_edit"] == reports_df_correct_pred["target"]

In [38]:
reports_df_correct_pred["acc_wrong_edit"].value_counts()

acc_wrong_edit
True     382
False    156
Name: count, dtype: int64

In [34]:
reports_df_incorrect_pred[reports_df_incorrect_pred["pred_wrong_edit"] != reports_df_incorrect_pred["target"]]["wrong_edit_same_no_edit_pred"].value_counts()

wrong_edit_same_no_edit_pred
False    301
True      63
Name: count, dtype: int64

In [26]:
reports_df_incorrect_pred[reports_df_incorrect_pred["wrong_edit_label"] == reports_df_incorrect_pred["pred_no_edit"]]

,target,pred_no_edit,gen_no_edit,pred_wrong_edit,gen_wrong_edit,pred_correct_edit,gen_correct_edit,qa_id,source_file,wrong_edit_label
0,baroque architecture,villa,The architectural style of this church is **Goth,villa,The architectural style of this church is **Rena,baroque architecture,The architectural style of this church is **Rena,1581,report_1581.xlsx,villa
14,europe,north america,The palace in the image is **Schloss N,north america,The palace is not located in North America. Based,europe,Europe,14524,report_14524.xlsx,north america
18,europe,south america,The lighthouse in the image is the **L,south america,South America,europe,Europe,10005,report_10005.xlsx,south america
20,europe,south america,Piazza San Marco is located in **Europe**,south america,The square shown is **Piazza San Marco**,europe,Europe,3717,report_3717.xlsx,south america
51,right,left,In the country where this church is located — **,left,left,right,In the country where this church is located — **,1491,report_1491.xlsx,left
...,...,...,...,...,...,...,...,...,...,...
435,europe,north america,This square is located in **Europe**.The,north america,The square shown in the image is located in **,europe,Europe,3930,report_3930.xlsx,north america
440,asia,antarctica,This mountain is **Mount K2** (also,north america,The mountain in the image is **not in Antarctica,asia,Asia,465945,report_465945.xlsx,antarctica
450,right,left,In the country where this monument is located ...,left,left,right,right,22496,report_22496.xlsx,left
460,right,left,The country where this castle is located is **...,left,left,right,Right-hand driveThe castle in the image is,22420,report_22420.xlsx,left
461,right,left,The driving side of **Greece** — the,left,left,right,right,3863,report_3863.xlsx,left

In [23]:
reports_df_incorrect_pred[reports_df_incorrect_pred["pred_correct_edit"] == reports_df_incorrect_pred["target"]]

,target,pred_no_edit,gen_no_edit,pred_wrong_edit,gen_wrong_edit,pred_correct_edit,gen_correct_edit,qa_id,source_file
5,baroque architecture,villa,The architectural style of this church is **Goth,villa,The architectural style of this church is **Rena,baroque architecture,The architectural style of this church is **Rena,1581,report_1581.xlsx
9,capital punishment,torture,"Actually, there is no patron saint associated ...",capital punishment,The cause of death of this church’s patron saint,capital punishment,The cause of death of this church’s patron saint,2312,report_2312.xlsx
10,europe,north america,The monastery in the image is **St. Michael,north america,The monastery in the image is located in **Europe,europe,Europe,150,report_150.xlsx
13,capital punishment,rebellion,The church in question is **Église Saint,rebellion,The cause of death of the person this church is,capital punishment,The cause of death of the person this church is,1081,report_1081.xlsx
14,1623,1618,The inventor of the motor vehicle — widely cre...,1623,"The inventor of the motor vehicle, Karl Benz,",1623,The inventor of the motor vehicle is typically...,225288,report_225288.xlsx
...,...,...,...,...,...,...,...,...,...
992,amsterdam,berlin,The church shown is the **St. Marien,berlin,Cologne,amsterdam,The capital of the country where this church i...,228066,report_228066.xlsx
995,9596961,11476747,The cultural heritage shown in the image is lo...,9596961,7358472 square kilometers,9596961,The area of the sovereign state where this cul...,468759,report_468759.xlsx
997,machaerus,england,The church in the image is **St. John,denmark,Norway,machaerus,Machaerus,40203,report_40203.xlsx
998,right,left,The country where this castle is located is **...,left,left,right,Right-hand driveThe castle in the image is,22420,report_22420.xlsx
999,right,left,The driving side of **Greece** — the,left,left,right,right,3863,report_3863.xlsx

In [9]:
wrong_edit = pd.read_pickle("/home/sgw3fy/jobs/standard_shortcut/projects/model_editing/datasets/reasonvqa/rvqa_wrong_edit_df.pkl")

In [11]:
wrong_edit.rename(columns={"answer": "wrong_edit_label"}, inplace=True)

In [ ]:
wrong_edit[["qa_id", "wrong_edit_label"]]

,uid,image,image_path,question,wrong_edit_label,rationale,cot,choices,idx_choices,qa_id
0,4355164,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,What continent is this house in?,africa,-,-,europe; south america; africa; antarctica,(A) europe\n(B) south america\n(C) africa\n(D)...,16
2,3959163,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,What country is this structure located in?,central african rep,-,-,russia; somalia; central african rep; dominica,(A) russia\n(B) somalia\n(C) central african r...,17
4,2600142,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,On which continent is this Rathaus located?,asia,-,-,europe; south america; asia; north america,(A) europe\n(B) south america\n(C) asia\n(D) n...,36
6,1857451,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,What country is this church in?,nauru,-,-,czech republic; singapore; saudi arabia; nauru,(A) czech republic\n(B) singapore\n(C) saudi a...,67
8,4424548,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,Who is the head of government of the successor...,edmund barton,-,-,petr fiala; fredrik reinfeldt; edmund barton; ...,(A) petr fiala\n(B) fredrik reinfeldt\n(C) edm...,80
...,...,...,...,...,...,...,...,...,...,...
2013033,4595167,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,What is the area of the original country of th...,491657,-,-,330803; 354001; 491657; 294470,(A) 330803\n(B) 354001\n(C) 491657\n(D) 294470,225413
3032598,4462157,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,Where was the inventor of the road vehicle bur...,poland,-,-,zhalan cemetery; switzerland; poland; wales,(A) zhalan cemetery\n(B) switzerland\n(C) pola...,225469
2275942,4508068,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,When was the motor vehicle invented?,1875,-,-,1884; 1879; 1890; 1875,(A) 1884\n(B) 1879\n(C) 1890\n(D) 1875,225485
3044023,4620192,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,When did the inventor of the motor vehicle die?,1690,-,-,1688; 1690; 1679; 1693,(A) 1688\n(B) 1690\n(C) 1679\n(D) 1693,225488
3030180,4443778,/home/sgw3fy/jobs/standard_shortcut/projects/m...,/home/sgw3fy/jobs/standard_shortcut/projects/m...,When was the road vehicle invented?,1880,-,-,1884; 1892; 1880; 1882,(A) 1884\n(B) 1892\n(C) 1880\n(D) 1882,226201